// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ColumnIndex.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from ColumnIndex.proto</summary>
public static partial class ColumnIndexReflection {

  #region Descriptor
  /// <summary>File descriptor for ColumnIndex.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static ColumnIndexReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChFDb2x1bW5JbmRleC5wcm90byKDAwoLQ29sdW1uSW5kZXgSDQoFbGV2ZWwY",
          "ASABKAUSEAoIc3RhcnRQdHIYAiABKAMSDgoGZW5kUHRyGAMgASgDEhsKBXJh",
          "bmdlGAQgASgLMgwuV2luZG93UmFuZ2USFgoOc3RhcnRNekxpc3RQdHIYBSAB",
          "KAMSFAoMZW5kTXpMaXN0UHRyGAYgASgDEhYKDnN0YXJ0UnRMaXN0UHRyGAcg",
          "ASgDEhQKDGVuZFJ0TGlzdFB0chgIIAEoAxIdChVzdGFydFNwZWNydGFJZExp",
          "c3RQdHIYCSABKAMSGwoTZW5kU3BlY3J0YUlkTGlzdFB0chgKIAEoAxIdChVz",
          "dGFydEludGVuc2l0eUxpc3RQdHIYCyABKAMSGwoTZW5kSW50ZW5zaXR5TGlz",
          "dFB0chgMIAEoAxILCgNtenMYDSADKAUSCwoDcnRzGA4gAygFEhIKCnNwZWN0",
          "cmFJZHMYDyADKAUSEwoLaW50ZW5zaXRpZXMYECADKAUSDwoHYW5jaG9ycxgR",
          "IAMoAyJXCgtXaW5kb3dSYW5nZRINCgVzdGFydBgBIAEoARILCgNlbmQYAiAB",
          "KAESCgoCbXoYAyABKAESDgoGY2hhcmdlGAQgASgFEhAKCGZlYXR1cmVzGAUg",
          "ASgJYgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::ColumnIndex), global::ColumnIndex.Parser, new[]{ "Level", "StartPtr", "EndPtr", "Range", "StartMzListPtr", "EndMzListPtr", "StartRtListPtr", "EndRtListPtr", "StartSpecrtaIdListPtr", "EndSpecrtaIdListPtr", "StartIntensityListPtr", "EndIntensityListPtr", "Mzs", "Rts", "SpectraIds", "Intensities", "Anchors" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::WindowRange), global::WindowRange.Parser, new[]{ "Start", "End", "Mz", "Charge", "Features" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class ColumnIndex : pb::IMessage<ColumnIndex>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<ColumnIndex> _parser = new pb::MessageParser<ColumnIndex>(() => new ColumnIndex());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<ColumnIndex> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ColumnIndexReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ColumnIndex() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ColumnIndex(ColumnIndex other) : this() {
    level_ = other.level_;
    startPtr_ = other.startPtr_;
    endPtr_ = other.endPtr_;
    range_ = other.range_ != null ? other.range_.Clone() : null;
    startMzListPtr_ = other.startMzListPtr_;
    endMzListPtr_ = other.endMzListPtr_;
    startRtListPtr_ = other.startRtListPtr_;
    endRtListPtr_ = other.endRtListPtr_;
    startSpecrtaIdListPtr_ = other.startSpecrtaIdListPtr_;
    endSpecrtaIdListPtr_ = other.endSpecrtaIdListPtr_;
    startIntensityListPtr_ = other.startIntensityListPtr_;
    endIntensityListPtr_ = other.endIntensityListPtr_;
    mzs_ = other.mzs_.Clone();
    rts_ = other.rts_.Clone();
    spectraIds_ = other.spectraIds_.Clone();
    intensities_ = other.intensities_.Clone();
    anchors_ = other.anchors_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ColumnIndex Clone() {
    return new ColumnIndex(this);
  }

  /// <summary>Field number for the "level" field.</summary>
  public const int LevelFieldNumber = 1;
  private int level_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Level {
    get { return level_; }
    set {
      level_ = value;
    }
  }

  /// <summary>Field number for the "startPtr" field.</summary>
  public const int StartPtrFieldNumber = 2;
  private long startPtr_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long StartPtr {
    get { return startPtr_; }
    set {
      startPtr_ = value;
    }
  }

  /// <summary>Field number for the "endPtr" field.</summary>
  public const int EndPtrFieldNumber = 3;
  private long endPtr_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long EndPtr {
    get { return endPtr_; }
    set {
      endPtr_ = value;
    }
  }

  /// <summary>Field number for the "range" field.</summary>
  public const int RangeFieldNumber = 4;
  private global::WindowRange range_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::WindowRange Range {
    get { return range_; }
    set {
      range_ = value;
    }
  }

  /// <summary>Field number for the "startMzListPtr" field.</summary>
  public const int StartMzListPtrFieldNumber = 5;
  private long startMzListPtr_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long StartMzListPtr {
    get { return startMzListPtr_; }
    set {
      startMzListPtr_ = value;
    }
  }

  /// <summary>Field number for the "endMzListPtr" field.</summary>
  public const int EndMzListPtrFieldNumber = 6;
  private long endMzListPtr_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long EndMzListPtr {
    get { return endMzListPtr_; }
    set {
      endMzListPtr_ = value;
    }
  }

  /// <summary>Field number for the "startRtListPtr" field.</summary>
  public const int StartRtListPtrFieldNumber = 7;
  private long startRtListPtr_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long StartRtListPtr {
    get { return startRtListPtr_; }
    set {
      startRtListPtr_ = value;
    }
  }

  /// <summary>Field number for the "endRtListPtr" field.</summary>
  public const int EndRtListPtrFieldNumber = 8;
  private long endRtListPtr_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long EndRtListPtr {
    get { return endRtListPtr_; }
    set {
      endRtListPtr_ = value;
    }
  }

  /// <summary>Field number for the "startSpecrtaIdListPtr" field.</summary>
  public const int StartSpecrtaIdListPtrFieldNumber = 9;
  private long startSpecrtaIdListPtr_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long StartSpecrtaIdListPtr {
    get { return startSpecrtaIdListPtr_; }
    set {
      startSpecrtaIdListPtr_ = value;
    }
  }

  /// <summary>Field number for the "endSpecrtaIdListPtr" field.</summary>
  public const int EndSpecrtaIdListPtrFieldNumber = 10;
  private long endSpecrtaIdListPtr_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long EndSpecrtaIdListPtr {
    get { return endSpecrtaIdListPtr_; }
    set {
      endSpecrtaIdListPtr_ = value;
    }
  }

  /// <summary>Field number for the "startIntensityListPtr" field.</summary>
  public const int StartIntensityListPtrFieldNumber = 11;
  private long startIntensityListPtr_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long StartIntensityListPtr {
    get { return startIntensityListPtr_; }
    set {
      startIntensityListPtr_ = value;
    }
  }

  /// <summary>Field number for the "endIntensityListPtr" field.</summary>
  public const int EndIntensityListPtrFieldNumber = 12;
  private long endIntensityListPtr_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long EndIntensityListPtr {
    get { return endIntensityListPtr_; }
    set {
      endIntensityListPtr_ = value;
    }
  }

  /// <summary>Field number for the "mzs" field.</summary>
  public const int MzsFieldNumber = 13;
  private static readonly pb::FieldCodec<int> _repeated_mzs_codec
      = pb::FieldCodec.ForInt32(106);
  private readonly pbc::RepeatedField<int> mzs_ = new pbc::RepeatedField<int>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<int> Mzs {
    get { return mzs_; }
  }

  /// <summary>Field number for the "rts" field.</summary>
  public const int RtsFieldNumber = 14;
  private static readonly pb::FieldCodec<int> _repeated_rts_codec
      = pb::FieldCodec.ForInt32(114);
  private readonly pbc::RepeatedField<int> rts_ = new pbc::RepeatedField<int>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<int> Rts {
    get { return rts_; }
  }

  /// <summary>Field number for the "spectraIds" field.</summary>
  public const int SpectraIdsFieldNumber = 15;
  private static readonly pb::FieldCodec<int> _repeated_spectraIds_codec
      = pb::FieldCodec.ForInt32(122);
  private readonly pbc::RepeatedField<int> spectraIds_ = new pbc::RepeatedField<int>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<int> SpectraIds {
    get { return spectraIds_; }
  }

  /// <summary>Field number for the "intensities" field.</summary>
  public const int IntensitiesFieldNumber = 16;
  private static readonly pb::FieldCodec<int> _repeated_intensities_codec
      = pb::FieldCodec.ForInt32(130);
  private readonly pbc::RepeatedField<int> intensities_ = new pbc::RepeatedField<int>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<int> Intensities {
    get { return intensities_; }
  }

  /// <summary>Field number for the "anchors" field.</summary>
  public const int AnchorsFieldNumber = 17;
  private static readonly pb::FieldCodec<long> _repeated_anchors_codec
      = pb::FieldCodec.ForInt64(138);
  private readonly pbc::RepeatedField<long> anchors_ = new pbc::RepeatedField<long>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<long> Anchors {
    get { return anchors_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as ColumnIndex);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(ColumnIndex other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Level != other.Level) return false;
    if (StartPtr != other.StartPtr) return false;
    if (EndPtr != other.EndPtr) return false;
    if (!object.Equals(Range, other.Range)) return false;
    if (StartMzListPtr != other.StartMzListPtr) return false;
    if (EndMzListPtr != other.EndMzListPtr) return false;
    if (StartRtListPtr != other.StartRtListPtr) return false;
    if (EndRtListPtr != other.EndRtListPtr) return false;
    if (StartSpecrtaIdListPtr != other.StartSpecrtaIdListPtr) return false;
    if (EndSpecrtaIdListPtr != other.EndSpecrtaIdListPtr) return false;
    if (StartIntensityListPtr != other.StartIntensityListPtr) return false;
    if (EndIntensityListPtr != other.EndIntensityListPtr) return false;
    if(!mzs_.Equals(other.mzs_)) return false;
    if(!rts_.Equals(other.rts_)) return false;
    if(!spectraIds_.Equals(other.spectraIds_)) return false;
    if(!intensities_.Equals(other.intensities_)) return false;
    if(!anchors_.Equals(other.anchors_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Level != 0) hash ^= Level.GetHashCode();
    if (StartPtr != 0L) hash ^= StartPtr.GetHashCode();
    if (EndPtr != 0L) hash ^= EndPtr.GetHashCode();
    if (range_ != null) hash ^= Range.GetHashCode();
    if (StartMzListPtr != 0L) hash ^= StartMzListPtr.GetHashCode();
    if (EndMzListPtr != 0L) hash ^= EndMzListPtr.GetHashCode();
    if (StartRtListPtr != 0L) hash ^= StartRtListPtr.GetHashCode();
    if (EndRtListPtr != 0L) hash ^= EndRtListPtr.GetHashCode();
    if (StartSpecrtaIdListPtr != 0L) hash ^= StartSpecrtaIdListPtr.GetHashCode();
    if (EndSpecrtaIdListPtr != 0L) hash ^= EndSpecrtaIdListPtr.GetHashCode();
    if (StartIntensityListPtr != 0L) hash ^= StartIntensityListPtr.GetHashCode();
    if (EndIntensityListPtr != 0L) hash ^= EndIntensityListPtr.GetHashCode();
    hash ^= mzs_.GetHashCode();
    hash ^= rts_.GetHashCode();
    hash ^= spectraIds_.GetHashCode();
    hash ^= intensities_.GetHashCode();
    hash ^= anchors_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Level != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(Level);
    }
    if (StartPtr != 0L) {
      output.WriteRawTag(16);
      output.WriteInt64(StartPtr);
    }
    if (EndPtr != 0L) {
      output.WriteRawTag(24);
      output.WriteInt64(EndPtr);
    }
    if (range_ != null) {
      output.WriteRawTag(34);
      output.WriteMessage(Range);
    }
    if (StartMzListPtr != 0L) {
      output.WriteRawTag(40);
      output.WriteInt64(StartMzListPtr);
    }
    if (EndMzListPtr != 0L) {
      output.WriteRawTag(48);
      output.WriteInt64(EndMzListPtr);
    }
    if (StartRtListPtr != 0L) {
      output.WriteRawTag(56);
      output.WriteInt64(StartRtListPtr);
    }
    if (EndRtListPtr != 0L) {
      output.WriteRawTag(64);
      output.WriteInt64(EndRtListPtr);
    }
    if (StartSpecrtaIdListPtr != 0L) {
      output.WriteRawTag(72);
      output.WriteInt64(StartSpecrtaIdListPtr);
    }
    if (EndSpecrtaIdListPtr != 0L) {
      output.WriteRawTag(80);
      output.WriteInt64(EndSpecrtaIdListPtr);
    }
    if (StartIntensityListPtr != 0L) {
      output.WriteRawTag(88);
      output.WriteInt64(StartIntensityListPtr);
    }
    if (EndIntensityListPtr != 0L) {
      output.WriteRawTag(96);
      output.WriteInt64(EndIntensityListPtr);
    }
    mzs_.WriteTo(output, _repeated_mzs_codec);
    rts_.WriteTo(output, _repeated_rts_codec);
    spectraIds_.WriteTo(output, _repeated_spectraIds_codec);
    intensities_.WriteTo(output, _repeated_intensities_codec);
    anchors_.WriteTo(output, _repeated_anchors_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Level != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(Level);
    }
    if (StartPtr != 0L) {
      output.WriteRawTag(16);
      output.WriteInt64(StartPtr);
    }
    if (EndPtr != 0L) {
      output.WriteRawTag(24);
      output.WriteInt64(EndPtr);
    }
    if (range_ != null) {
      output.WriteRawTag(34);
      output.WriteMessage(Range);
    }
    if (StartMzListPtr != 0L) {
      output.WriteRawTag(40);
      output.WriteInt64(StartMzListPtr);
    }
    if (EndMzListPtr != 0L) {
      output.WriteRawTag(48);
      output.WriteInt64(EndMzListPtr);
    }
    if (StartRtListPtr != 0L) {
      output.WriteRawTag(56);
      output.WriteInt64(StartRtListPtr);
    }
    if (EndRtListPtr != 0L) {
      output.WriteRawTag(64);
      output.WriteInt64(EndRtListPtr);
    }
    if (StartSpecrtaIdListPtr != 0L) {
      output.WriteRawTag(72);
      output.WriteInt64(StartSpecrtaIdListPtr);
    }
    if (EndSpecrtaIdListPtr != 0L) {
      output.WriteRawTag(80);
      output.WriteInt64(EndSpecrtaIdListPtr);
    }
    if (StartIntensityListPtr != 0L) {
      output.WriteRawTag(88);
      output.WriteInt64(StartIntensityListPtr);
    }
    if (EndIntensityListPtr != 0L) {
      output.WriteRawTag(96);
      output.WriteInt64(EndIntensityListPtr);
    }
    mzs_.WriteTo(ref output, _repeated_mzs_codec);
    rts_.WriteTo(ref output, _repeated_rts_codec);
    spectraIds_.WriteTo(ref output, _repeated_spectraIds_codec);
    intensities_.WriteTo(ref output, _repeated_intensities_codec);
    anchors_.WriteTo(ref output, _repeated_anchors_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Level != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Level);
    }
    if (StartPtr != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(StartPtr);
    }
    if (EndPtr != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(EndPtr);
    }
    if (range_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Range);
    }
    if (StartMzListPtr != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(StartMzListPtr);
    }
    if (EndMzListPtr != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(EndMzListPtr);
    }
    if (StartRtListPtr != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(StartRtListPtr);
    }
    if (EndRtListPtr != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(EndRtListPtr);
    }
    if (StartSpecrtaIdListPtr != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(StartSpecrtaIdListPtr);
    }
    if (EndSpecrtaIdListPtr != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(EndSpecrtaIdListPtr);
    }
    if (StartIntensityListPtr != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(StartIntensityListPtr);
    }
    if (EndIntensityListPtr != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(EndIntensityListPtr);
    }
    size += mzs_.CalculateSize(_repeated_mzs_codec);
    size += rts_.CalculateSize(_repeated_rts_codec);
    size += spectraIds_.CalculateSize(_repeated_spectraIds_codec);
    size += intensities_.CalculateSize(_repeated_intensities_codec);
    size += anchors_.CalculateSize(_repeated_anchors_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(ColumnIndex other) {
    if (other == null) {
      return;
    }
    if (other.Level != 0) {
      Level = other.Level;
    }
    if (other.StartPtr != 0L) {
      StartPtr = other.StartPtr;
    }
    if (other.EndPtr != 0L) {
      EndPtr = other.EndPtr;
    }
    if (other.range_ != null) {
      if (range_ == null) {
        Range = new global::WindowRange();
      }
      Range.MergeFrom(other.Range);
    }
    if (other.StartMzListPtr != 0L) {
      StartMzListPtr = other.StartMzListPtr;
    }
    if (other.EndMzListPtr != 0L) {
      EndMzListPtr = other.EndMzListPtr;
    }
    if (other.StartRtListPtr != 0L) {
      StartRtListPtr = other.StartRtListPtr;
    }
    if (other.EndRtListPtr != 0L) {
      EndRtListPtr = other.EndRtListPtr;
    }
    if (other.StartSpecrtaIdListPtr != 0L) {
      StartSpecrtaIdListPtr = other.StartSpecrtaIdListPtr;
    }
    if (other.EndSpecrtaIdListPtr != 0L) {
      EndSpecrtaIdListPtr = other.EndSpecrtaIdListPtr;
    }
    if (other.StartIntensityListPtr != 0L) {
      StartIntensityListPtr = other.StartIntensityListPtr;
    }
    if (other.EndIntensityListPtr != 0L) {
      EndIntensityListPtr = other.EndIntensityListPtr;
    }
    mzs_.Add(other.mzs_);
    rts_.Add(other.rts_);
    spectraIds_.Add(other.spectraIds_);
    intensities_.Add(other.intensities_);
    anchors_.Add(other.anchors_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Level = input.ReadInt32();
          break;
        }
        case 16: {
          StartPtr = input.ReadInt64();
          break;
        }
        case 24: {
          EndPtr = input.ReadInt64();
          break;
        }
        case 34: {
          if (range_ == null) {
            Range = new global::WindowRange();
          }
          input.ReadMessage(Range);
          break;
        }
        case 40: {
          StartMzListPtr = input.ReadInt64();
          break;
        }
        case 48: {
          EndMzListPtr = input.ReadInt64();
          break;
        }
        case 56: {
          StartRtListPtr = input.ReadInt64();
          break;
        }
        case 64: {
          EndRtListPtr = input.ReadInt64();
          break;
        }
        case 72: {
          StartSpecrtaIdListPtr = input.ReadInt64();
          break;
        }
        case 80: {
          EndSpecrtaIdListPtr = input.ReadInt64();
          break;
        }
        case 88: {
          StartIntensityListPtr = input.ReadInt64();
          break;
        }
        case 96: {
          EndIntensityListPtr = input.ReadInt64();
          break;
        }
        case 106:
        case 104: {
          mzs_.AddEntriesFrom(input, _repeated_mzs_codec);
          break;
        }
        case 114:
        case 112: {
          rts_.AddEntriesFrom(input, _repeated_rts_codec);
          break;
        }
        case 122:
        case 120: {
          spectraIds_.AddEntriesFrom(input, _repeated_spectraIds_codec);
          break;
        }
        case 130:
        case 128: {
          intensities_.AddEntriesFrom(input, _repeated_intensities_codec);
          break;
        }
        case 138:
        case 136: {
          anchors_.AddEntriesFrom(input, _repeated_anchors_codec);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Level = input.ReadInt32();
          break;
        }
        case 16: {
          StartPtr = input.ReadInt64();
          break;
        }
        case 24: {
          EndPtr = input.ReadInt64();
          break;
        }
        case 34: {
          if (range_ == null) {
            Range = new global::WindowRange();
          }
          input.ReadMessage(Range);
          break;
        }
        case 40: {
          StartMzListPtr = input.ReadInt64();
          break;
        }
        case 48: {
          EndMzListPtr = input.ReadInt64();
          break;
        }
        case 56: {
          StartRtListPtr = input.ReadInt64();
          break;
        }
        case 64: {
          EndRtListPtr = input.ReadInt64();
          break;
        }
        case 72: {
          StartSpecrtaIdListPtr = input.ReadInt64();
          break;
        }
        case 80: {
          EndSpecrtaIdListPtr = input.ReadInt64();
          break;
        }
        case 88: {
          StartIntensityListPtr = input.ReadInt64();
          break;
        }
        case 96: {
          EndIntensityListPtr = input.ReadInt64();
          break;
        }
        case 106:
        case 104: {
          mzs_.AddEntriesFrom(ref input, _repeated_mzs_codec);
          break;
        }
        case 114:
        case 112: {
          rts_.AddEntriesFrom(ref input, _repeated_rts_codec);
          break;
        }
        case 122:
        case 120: {
          spectraIds_.AddEntriesFrom(ref input, _repeated_spectraIds_codec);
          break;
        }
        case 130:
        case 128: {
          intensities_.AddEntriesFrom(ref input, _repeated_intensities_codec);
          break;
        }
        case 138:
        case 136: {
          anchors_.AddEntriesFrom(ref input, _repeated_anchors_codec);
          break;
        }
      }
    }
  }
  #endif

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class WindowRange : pb::IMessage<WindowRange>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<WindowRange> _parser = new pb::MessageParser<WindowRange>(() => new WindowRange());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<WindowRange> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ColumnIndexReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public WindowRange() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public WindowRange(WindowRange other) : this() {
    start_ = other.start_;
    end_ = other.end_;
    mz_ = other.mz_;
    charge_ = other.charge_;
    features_ = other.features_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public WindowRange Clone() {
    return new WindowRange(this);
  }

  /// <summary>Field number for the "start" field.</summary>
  public const int StartFieldNumber = 1;
  private double start_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public double Start {
    get { return start_; }
    set {
      start_ = value;
    }
  }

  /// <summary>Field number for the "end" field.</summary>
  public const int EndFieldNumber = 2;
  private double end_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public double End {
    get { return end_; }
    set {
      end_ = value;
    }
  }

  /// <summary>Field number for the "mz" field.</summary>
  public const int MzFieldNumber = 3;
  private double mz_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public double Mz {
    get { return mz_; }
    set {
      mz_ = value;
    }
  }

  /// <summary>Field number for the "charge" field.</summary>
  public const int ChargeFieldNumber = 4;
  private int charge_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Charge {
    get { return charge_; }
    set {
      charge_ = value;
    }
  }

  /// <summary>Field number for the "features" field.</summary>
  public const int FeaturesFieldNumber = 5;
  private string features_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Features {
    get { return features_; }
    set {
      features_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as WindowRange);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(WindowRange other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Start, other.Start)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(End, other.End)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Mz, other.Mz)) return false;
    if (Charge != other.Charge) return false;
    if (Features != other.Features) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Start != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Start);
    if (End != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(End);
    if (Mz != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Mz);
    if (Charge != 0) hash ^= Charge.GetHashCode();
    if (Features.Length != 0) hash ^= Features.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Start != 0D) {
      output.WriteRawTag(9);
      output.WriteDouble(Start);
    }
    if (End != 0D) {
      output.WriteRawTag(17);
      output.WriteDouble(End);
    }
    if (Mz != 0D) {
      output.WriteRawTag(25);
      output.WriteDouble(Mz);
    }
    if (Charge != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(Charge);
    }
    if (Features.Length != 0) {
      output.WriteRawTag(42);
      output.WriteString(Features);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Start != 0D) {
      output.WriteRawTag(9);
      output.WriteDouble(Start);
    }
    if (End != 0D) {
      output.WriteRawTag(17);
      output.WriteDouble(End);
    }
    if (Mz != 0D) {
      output.WriteRawTag(25);
      output.WriteDouble(Mz);
    }
    if (Charge != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(Charge);
    }
    if (Features.Length != 0) {
      output.WriteRawTag(42);
      output.WriteString(Features);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Start != 0D) {
      size += 1 + 8;
    }
    if (End != 0D) {
      size += 1 + 8;
    }
    if (Mz != 0D) {
      size += 1 + 8;
    }
    if (Charge != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Charge);
    }
    if (Features.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Features);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(WindowRange other) {
    if (other == null) {
      return;
    }
    if (other.Start != 0D) {
      Start = other.Start;
    }
    if (other.End != 0D) {
      End = other.End;
    }
    if (other.Mz != 0D) {
      Mz = other.Mz;
    }
    if (other.Charge != 0) {
      Charge = other.Charge;
    }
    if (other.Features.Length != 0) {
      Features = other.Features;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 9: {
          Start = input.ReadDouble();
          break;
        }
        case 17: {
          End = input.ReadDouble();
          break;
        }
        case 25: {
          Mz = input.ReadDouble();
          break;
        }
        case 32: {
          Charge = input.ReadInt32();
          break;
        }
        case 42: {
          Features = input.ReadString();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 9: {
          Start = input.ReadDouble();
          break;
        }
        case 17: {
          End = input.ReadDouble();
          break;
        }
        case 25: {
          Mz = input.ReadDouble();
          break;
        }
        case 32: {
          Charge = input.ReadInt32();
          break;
        }
        case 42: {
          Features = input.ReadString();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
